### ISSUE TITLE
Picroft hanging up and overheating

### ISSUE THREAD

**Issue by jerryar** [MycroftAI/mycroft-timer#13]
When activating the "timer" function on Picroft (RPi3B) with the words "Mycroft set the timer for one minute", Mycroft responds with "Timer started for one minute" . At that point the "Skills" "Debug" goes into a continuous loop, Mycroft has hanged and will not respond to further commands. A thermometer icon appears after a minute or so, and the CPU heatsink actually feels hot. Rebooting Picroft restores normal function responding to voice commands.

**Comment by KathyReid** [comment]
Thanks @jerryar for raising this Issue. 
I will take it first and see if I can replicate it, and run `htop` to see if there is a runaway process.

**Comment by penrods** [comment]
Should be fixed by #15, just merged

**Comment by jerryar** [comment]
Steve, Thanks for your work on this issue.

Jerrya
