### ISSUE TITLE
Show timer on faceplate

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-timer#3]
`Set a 3 minute timer`
Would be nice to have it show the countdown on the faceplate and maybe cycle through if there are multiple.

**Comment by nevercast** [comment]
Mentioned here https://github.com/MycroftAI/mycroft-timer/blob/master/__init__.py#L87

**Comment by penrods** [comment]
Fixed by #10

**Comment by MatthewScholefield** [comment]
Will leave open until we get the pieces in place and show the actual count down on the faceplate

**Comment by penrods** [comment]
Addressed even better in #21
