### ISSUE TITLE
Create 3 minute timer

### ISSUE THREAD

**Issue by MatthewScholefield** [MycroftAI/mycroft-timer#4]
`create a 3 minute timer`

`How much time is left on the timer`
> There is 2 minutes left on the create a 3 minute timer

**Comment by nevercast** [comment]
When recalling the time, integer division is used. So 2 minutes, 55 seconds. Is still 2 minutes. 
https://github.com/MycroftAI/mycroft-timer/blob/master/__init__.py#L40-L43

Without implementing approximations in the speech, Mycroft's answer is correct. There is at least 2 minutes, and less than 3 minutes remaining. Perhaps a better alternative is if the `minutes - int(minutes)` > .5f, then the speech is something like `"Just under {} minute{s} remaining" ( int(minutes)+1`

So 2 minutes, 31 seconds would be "Just under 3 minutes remaining"

**Comment by penrods** [comment]
Fixed by #10
