### ISSUE TITLE
Possible bug in cancel handler

### ISSUE THREAD

**Issue by nevercast** [MycroftAI/mycroft-timer#9]
https://github.com/MycroftAI/mycroft-timer/blob/master/__init__.py#L201

I don't see `duration` defined in this function, no nonlocal, global or self reference either.

I suspect it was copied from something like this https://github.com/MycroftAI/mycroft-timer/blob/master/__init__.py#L167-L168

In which case, `intent['duration']` should be used.

**Comment by penrods** [comment]
Fixed by #10
